// GENERATED by tools/gen_tokens.py from the @scshafe/ui token registry. Do not edit:
// change the registry in scshafe-ui, then run `uv run python tools/gen_tokens.py --refresh`.
//
// Source:   @scshafe/ui 0.3.1 (lib/tokens.js, sha256 8e12d3f3037327f3), commit 426d87340d54
// Registry: sha256:23d14d4e53cce6a6843b81b122879292375f2a0c390c716e73a387a7c5a67b47 (62 tokens)
//
// Every registry token is a property here, named in camelCase without the prefix
// (--sui-text-strong -> textStrong). Themed tokens switch with `dark`; lengths are
// logical pixels (CSS px), durations milliseconds, shadows
// { offsetX, offsetY, blur, spread, color }. `registry` maps CSS names to properties.
pragma Singleton
import QtQuick

QtObject {
    id: theme

    // ---- Theme selection ------------------------------------------------
    // "system" follows the OS colour scheme (Qt.styleHints.colorScheme);
    // "light" and "dark" pin a theme. Any other value behaves as "system".
    property string mode: "system"
    // The OS scheme, bound to Qt.styleHints.colorScheme. Apps leave it alone; tests
    // assign it to simulate the OS (the offscreen platform always reports Unknown).
    property int systemColorScheme: Qt.styleHints.colorScheme
    readonly property bool systemDark: systemColorScheme === Qt.ColorScheme.Dark
    readonly property bool dark: mode === "dark" || (mode !== "light" && systemDark)
    readonly property string themeName: dark ? "dark" : "light"

    // Reduced motion. Qt (through 6.11) exposes no OS reduced-motion preference
    // (QStyleHints has none; QAccessibilityHints, 6.10+, only has contrastPreference),
    // so the application sets this explicitly; when true every duration is 0.
    property bool reducedMotion: false

    // ---- Provenance -----------------------------------------------------
    readonly property string registryVersion: "0.3.1"
    readonly property string registryHash: "sha256:23d14d4e53cce6a6843b81b122879292375f2a0c390c716e73a387a7c5a67b47"

    // ---- color -------------------------------------------------------------
    // --sui-text: Body text colour.
    readonly property color text: dark ? "#eff6ff" : "#1b2533"
    // --sui-text-strong: Emphasised text (titles, strong).
    readonly property color textStrong: dark ? "#f8fbff" : "#0b1220"
    // --sui-muted: Secondary text, labels and hints.
    readonly property color muted: dark ? "#9fb0c8" : "#465366"
    // --sui-blue: Base blue; the default accent.
    readonly property color blue: dark ? "#6cb6ff" : "#0a4f99"
    // --sui-accent: Accent for links, focus and primary actions.
    readonly property color accent: theme.blue
    // --sui-accent-hover: Accent on hover.
    readonly property color accentHover: dark ? "#8cc8ff" : "#083f78"
    // --sui-accent-subtle: Accent-tinted background (selection, user messages).
    readonly property color accentSubtle: dark ? Qt.rgba(108 / 255, 182 / 255, 255 / 255, 0.11) : Qt.rgba(10 / 255, 79 / 255, 153 / 255, 0.1)
    // --sui-green: Base green; the default success colour.
    readonly property color green: dark ? "#52d273" : "#11602a"
    // --sui-ok: Success / healthy state.
    readonly property color ok: theme.green
    // --sui-ok-subtle: Success-tinted background.
    readonly property color okSubtle: dark ? Qt.rgba(82 / 255, 210 / 255, 115 / 255, 0.08) : Qt.rgba(17 / 255, 96 / 255, 42 / 255, 0.1)
    // --sui-tone-green: Green tone base (tints and borders).
    readonly property color toneGreen: theme.green
    // --sui-tone-green-text: Text on a green tint.
    readonly property color toneGreenText: dark ? "#bff8c9" : "#0f5a26"
    // --sui-tone-blue: Blue tone base (tints and borders).
    readonly property color toneBlue: theme.blue
    // --sui-tone-blue-text: Text on a blue tint.
    readonly property color toneBlueText: dark ? "#cae5ff" : "#0550ae"
    // --sui-tone-yellow: Yellow tone base (tints and borders).
    readonly property color toneYellow: dark ? "#f5c542" : "#9a6700"
    // --sui-tone-yellow-text: Text on a yellow tint.
    readonly property color toneYellowText: dark ? "#ffe8a3" : "#7d4e00"
    // --sui-tone-orange: Orange tone base (tints and borders).
    readonly property color toneOrange: dark ? "#ff9f43" : "#bc4c00"
    // --sui-tone-orange-text: Text on a orange tint.
    readonly property color toneOrangeText: dark ? "#ffd2a4" : "#953800"
    // --sui-tone-red: Red tone base (tints and borders).
    readonly property color toneRed: dark ? "#ff6b6b" : "#cf222e"
    // --sui-tone-red-text: Text on a red tint.
    readonly property color toneRedText: dark ? "#ffc4c4" : "#a40e26"
    // --sui-tone-purple: Purple tone base (tints and borders).
    readonly property color tonePurple: dark ? "#b18cff" : "#8250df"
    // --sui-tone-purple-text: Text on a purple tint.
    readonly property color tonePurpleText: dark ? "#dfd2ff" : "#6639ba"

    // ---- surface -----------------------------------------------------------
    // --sui-bg: Page background.
    readonly property color bg: dark ? "#08111f" : "#f6f8fb"
    // --sui-panel: Panel background.
    readonly property color panel: dark ? "#111d2f" : "#ffffff"
    // --sui-card: Card and message-bubble background.
    readonly property color card: dark ? Qt.rgba(17 / 255, 29 / 255, 47 / 255, 0.82) : "#ffffff"
    // --sui-bg-elevated: Raised surface (rails, menus).
    readonly property color bgElevated: dark ? Qt.rgba(18 / 255, 31 / 255, 50 / 255, 0.72) : "#eef2f7"
    // --sui-surface-2: Secondary surface; defaults to the elevated surface.
    readonly property color surface2: theme.bgElevated
    // --sui-popover: Popover, tooltip, dialog and toast background.
    readonly property color popover: dark ? Qt.rgba(8 / 255, 17 / 255, 31 / 255, 0.96) : Qt.rgba(255 / 255, 255 / 255, 255 / 255, 0.98)
    // --sui-field: Form control and button background.
    readonly property color field: dark ? Qt.rgba(8 / 255, 17 / 255, 31 / 255, 0.5) : "#ffffff"
    // --sui-bg-hover: Row / item hover background.
    readonly property color bgHover: dark ? Qt.rgba(108 / 255, 182 / 255, 255 / 255, 0.06) : Qt.rgba(10 / 255, 79 / 255, 153 / 255, 0.06)
    // --sui-tint: Neutral tint that sets a block off its surface (rows, readers, pills).
    readonly property color tint: dark ? Qt.rgba(255 / 255, 255 / 255, 255 / 255, 0.04) : Qt.rgba(15 / 255, 23 / 255, 42 / 255, 0.035)
    // --sui-code-bg: Code and preformatted-text background.
    readonly property color codeBg: dark ? Qt.rgba(4 / 255, 10 / 255, 20 / 255, 0.58) : Qt.rgba(15 / 255, 23 / 255, 42 / 255, 0.05)
    // --sui-backdrop: Scrim behind modal dialogs and popovers.
    readonly property color backdrop: dark ? Qt.rgba(0 / 255, 0 / 255, 0 / 255, 0.5) : Qt.rgba(15 / 255, 23 / 255, 42 / 255, 0.35)

    // ---- border ------------------------------------------------------------
    // --sui-line: Default hairline and divider.
    readonly property color line: dark ? Qt.rgba(183 / 255, 203 / 255, 231 / 255, 0.18) : Qt.rgba(31 / 255, 45 / 255, 66 / 255, 0.16)
    // --sui-border: Component border; defaults to the hairline.
    readonly property color border: theme.line
    // --sui-border-strong: Stronger border for floating layers.
    readonly property color borderStrong: dark ? Qt.rgba(183 / 255, 203 / 255, 231 / 255, 0.28) : Qt.rgba(31 / 255, 45 / 255, 66 / 255, 0.28)
    // --sui-border-hover: Border on hover / focus-within.
    readonly property color borderHover: dark ? Qt.rgba(108 / 255, 182 / 255, 255 / 255, 0.36) : Qt.rgba(10 / 255, 79 / 255, 153 / 255, 0.45)
    // --sui-field-border: Boundary of a form control (3:1 against its surroundings).
    readonly property color fieldBorder: dark ? "#6b7c93" : "#6b778a"
    // --sui-focus-ring: Keyboard focus indicator (:focus-visible outline).
    readonly property color focusRing: theme.accent

    // ---- shadow ------------------------------------------------------------
    // --sui-shadow: Panel shadow.
    readonly property var shadow: dark ? ({ offsetX: 0, offsetY: 10, blur: 34, spread: 0, color: Qt.rgba(0 / 255, 0 / 255, 0 / 255, 0.22) }) : ({ offsetX: 0, offsetY: 10, blur: 34, spread: 0, color: Qt.rgba(15 / 255, 23 / 255, 42 / 255, 0.1) })
    // --sui-shadow-lg: Popover, dialog and toast shadow.
    readonly property var shadowLg: dark ? ({ offsetX: 0, offsetY: 16, blur: 40, spread: 0, color: Qt.rgba(0 / 255, 0 / 255, 0 / 255, 0.34) }) : ({ offsetX: 0, offsetY: 16, blur: 40, spread: 0, color: Qt.rgba(15 / 255, 23 / 255, 42 / 255, 0.16) })
    // --sui-shadow-color: Colour of small, directional shadows (pinned columns, raised buttons).
    readonly property color shadowColor: dark ? Qt.rgba(0 / 255, 0 / 255, 0 / 255, 0.22) : Qt.rgba(15 / 255, 23 / 255, 42 / 255, 0.12)

    // ---- radius ------------------------------------------------------------
    // --sui-radius-sm: Small corner radius (chips, inputs).
    readonly property int radiusSm: 6
    // --sui-radius-md: Medium corner radius.
    readonly property int radiusMd: 8
    // --sui-radius: Default corner radius.
    readonly property int radius: theme.radiusMd
    // --sui-radius-lg: Large corner radius (cards, bubbles).
    readonly property int radiusLg: 10

    // ---- font --------------------------------------------------------------
    // --sui-mono: Monospace face for ids, code and keys.
    readonly property string mono: "ui-monospace, SFMono-Regular, Menlo, monospace"
    // --sui-chat-text-size: MessageBubble body text size.
    readonly property int chatTextSize: 13

    // ---- motion ------------------------------------------------------------
    // --sui-duration: Duration of every transition; 0s under prefers-reduced-motion: reduce.
    readonly property int duration: reducedMotion ? 0 : 120

    // ---- clamp -------------------------------------------------------------
    // --sui-clamp-2xs: Card body clamp, 2xs.
    readonly property int clamp2xs: 80
    // --sui-clamp-xs: Card body clamp, xs.
    readonly property int clampXs: 120
    // --sui-clamp-sm: Card body clamp, sm.
    readonly property int clampSm: 160
    // --sui-clamp-md: Card body clamp, md.
    readonly property int clampMd: 200
    // --sui-clamp-lg: Card body clamp, lg.
    readonly property int clampLg: 280
    // --sui-clamp-xl: Card body clamp, xl.
    readonly property int clampXl: 360

    // ---- space -------------------------------------------------------------
    // --sui-space-none: Spacing step none.
    readonly property int spaceNone: 0
    // --sui-space-xs: Spacing step xs.
    readonly property int spaceXs: 4
    // --sui-space-sm: Spacing step sm.
    readonly property int spaceSm: 8
    // --sui-space-md: Spacing step md.
    readonly property int spaceMd: 12
    // --sui-space-lg: Spacing step lg.
    readonly property int spaceLg: 16
    // --sui-space-xl: Spacing step xl.
    readonly property int spaceXl: 24
    // --sui-space-2xl: Spacing step 2xl.
    readonly property int space2xl: 32

    // CSS custom property -> property name, for tooling and tests.
    readonly property var registry: ({
        "--sui-text": "text",
        "--sui-text-strong": "textStrong",
        "--sui-muted": "muted",
        "--sui-blue": "blue",
        "--sui-accent": "accent",
        "--sui-accent-hover": "accentHover",
        "--sui-accent-subtle": "accentSubtle",
        "--sui-green": "green",
        "--sui-ok": "ok",
        "--sui-ok-subtle": "okSubtle",
        "--sui-tone-green": "toneGreen",
        "--sui-tone-green-text": "toneGreenText",
        "--sui-tone-blue": "toneBlue",
        "--sui-tone-blue-text": "toneBlueText",
        "--sui-tone-yellow": "toneYellow",
        "--sui-tone-yellow-text": "toneYellowText",
        "--sui-tone-orange": "toneOrange",
        "--sui-tone-orange-text": "toneOrangeText",
        "--sui-tone-red": "toneRed",
        "--sui-tone-red-text": "toneRedText",
        "--sui-tone-purple": "tonePurple",
        "--sui-tone-purple-text": "tonePurpleText",
        "--sui-bg": "bg",
        "--sui-panel": "panel",
        "--sui-card": "card",
        "--sui-bg-elevated": "bgElevated",
        "--sui-surface-2": "surface2",
        "--sui-popover": "popover",
        "--sui-field": "field",
        "--sui-bg-hover": "bgHover",
        "--sui-tint": "tint",
        "--sui-code-bg": "codeBg",
        "--sui-backdrop": "backdrop",
        "--sui-line": "line",
        "--sui-border": "border",
        "--sui-border-strong": "borderStrong",
        "--sui-border-hover": "borderHover",
        "--sui-field-border": "fieldBorder",
        "--sui-focus-ring": "focusRing",
        "--sui-shadow": "shadow",
        "--sui-shadow-lg": "shadowLg",
        "--sui-shadow-color": "shadowColor",
        "--sui-radius-sm": "radiusSm",
        "--sui-radius-md": "radiusMd",
        "--sui-radius": "radius",
        "--sui-radius-lg": "radiusLg",
        "--sui-mono": "mono",
        "--sui-chat-text-size": "chatTextSize",
        "--sui-duration": "duration",
        "--sui-clamp-2xs": "clamp2xs",
        "--sui-clamp-xs": "clampXs",
        "--sui-clamp-sm": "clampSm",
        "--sui-clamp-md": "clampMd",
        "--sui-clamp-lg": "clampLg",
        "--sui-clamp-xl": "clampXl",
        "--sui-space-none": "spaceNone",
        "--sui-space-xs": "spaceXs",
        "--sui-space-sm": "spaceSm",
        "--sui-space-md": "spaceMd",
        "--sui-space-lg": "spaceLg",
        "--sui-space-xl": "spaceXl",
        "--sui-space-2xl": "space2xl"
    })

    // ==== NATIVE-ONLY TOKENS =============================================
    // Not in the @scshafe/ui registry: defined in tools/gen_tokens.py (the
    // NATIVE-ONLY section) and checked by tests/test_tokens.py. Values the web
    // library writes as literals in components.css live here too, so native
    // components share them. Changing one is a scshafe-qt change.

    // ---- Focus, disabled, control metrics ------------------------------
    readonly property int focusRingWidth: 2       // :focus-visible outline width
    readonly property int focusRingOffset: 2      // :focus-visible outline-offset
    readonly property real disabledOpacity: 0.48  // .sui-button:disabled
    readonly property int controlPaddingX: 10     // .sui-button padding
    readonly property int controlPaddingY: 6
    readonly property int controlHeight: 28       // buttons, fields, icon buttons
    readonly property int rowHeight: 30           // sidebar items
    readonly property int listRowHeight: 52       // two-line list rows
    readonly property int chipHeight: 20
    readonly property int badgeHeight: 18
    readonly property int iconSize: 16
    readonly property int iconSizeSm: 12
    readonly property int statusDotSize: 8
    readonly property int splitterHandleWidth: 8  // hit area; the drawn line is 1px
    readonly property int splitterStep: 16        // arrow-key resize step (Shift: x4)

    // ---- Layout defaults ------------------------------------------------
    readonly property int sidebarWidth: 232
    readonly property int sidebarMinWidth: 160
    readonly property int sidebarMaxWidth: 400
    readonly property int inspectorWidth: 320
    readonly property int inspectorMinWidth: 240
    readonly property int inspectorMaxWidth: 560
    readonly property int contentMinWidth: 280
    readonly property int dialogWidth: 440
    readonly property int sheetWidth: 400
    readonly property int toastWidth: 360
    readonly property int toastTimeout: 5000      // ms a toast stays (0 = until dismissed)

    // ---- Type scale (pixel sizes the stylesheets use) and weights -------
    readonly property int fontSizeXs: 11
    readonly property int fontSizeSm: 12
    readonly property int fontSizeMd: 13
    readonly property int fontSizeBase: 14
    readonly property int fontSizeLg: 16
    readonly property int fontSizeXl: 18
    readonly property int fontSize2xl: 20
    readonly property int fontSize3xl: 24
    readonly property int fontWeightNormal: Font.Normal
    readonly property int fontWeightStrong: Font.DemiBold  // 600
    readonly property int fontWeightBold: Font.Bold        // 700

    // ---- Monospace face ---------------------------------------------------
    // --sui-mono is a CSS stack; Qt takes one family. `monoFamily` is the first
    // installed candidate for the platform (assign it to override):
    //   macos: SF Mono, Menlo, Monaco
    //   windows: Cascadia Mono, Consolas, Courier New
    //   linux: monospace, DejaVu Sans Mono, Noto Sans Mono, Liberation Mono, Ubuntu Mono
    //   fallback: monospace
    readonly property string platformName: Qt.platform.os === "osx" || Qt.platform.os === "macos" ? "macos"
        : Qt.platform.os === "windows" ? "windows" : "linux"
    readonly property var monoCandidates: ({ macos: ["SF Mono", "Menlo", "Monaco"], windows: ["Cascadia Mono", "Consolas", "Courier New"], linux: ["monospace", "DejaVu Sans Mono", "Noto Sans Mono", "Liberation Mono", "Ubuntu Mono"] })[platformName]
    property string monoFamily: _firstInstalled(monoCandidates, "monospace")

    // ---- Tones ------------------------------------------------------------
    // A tone is "neutral" | "info" | "ok" | "warn" | "danger", a bucket
    // "bucket1".."bucket8" (or its number), or a registry tone name
    // ("green", "blue", "yellow", "orange", "red", "purple").
    // toneBase: dot / border / tint colour; toneText: text on toneFill.
    readonly property real toneTint: 0.12     // fill under tone text (contrast-checked)
    readonly property real toneBorderAmount: 0.45
    readonly property var statusTones: ["neutral", "info", "ok", "warn", "danger"]

    // ---- Bucket palette (8 categorical tones) --------------------------
    // bucket1: blue
    readonly property color bucket1: dark ? "#6dadff" : "#2f7dd9"
    readonly property color bucket1Text: dark ? "#96c4ff" : "#0053a4"
    // bucket2: teal
    readonly property color bucket2: dark ? "#03c3c3" : "#018a8b"
    readonly property color bucket2Text: dark ? "#36d5d5" : "#045f5f"
    // bucket3: green
    readonly property color bucket3: dark ? "#67c377" : "#108f3b"
    readonly property color bucket3Text: dark ? "#83d48f" : "#046325"
    // bucket4: olive
    readonly property color bucket4: dark ? "#adb33c" : "#7e8205"
    readonly property color bucket4Text: dark ? "#c0c661" : "#565901"
    // bucket5: amber
    readonly property color bucket5: dark ? "#db9e2e" : "#a47204"
    readonly property color bucket5Text: dark ? "#ebb55a" : "#714e04"
    // bucket6: rust
    readonly property color bucket6: dark ? "#f58967" : "#cd5630"
    readonly property color bucket6Text: dark ? "#fea88d" : "#9c2e00"
    // bucket7: rose
    readonly property color bucket7: dark ? "#ee83af" : "#c65085"
    readonly property color bucket7Text: dark ? "#fea5c8" : "#9a265f"
    // bucket8: violet
    readonly property color bucket8: dark ? "#b995f6" : "#9065d0"
    readonly property color bucket8Text: dark ? "#cdb3ff" : "#6a3ea5"
    readonly property int bucketCount: 8
    readonly property var bucketNames: ["blue", "teal", "green", "olive", "amber", "rust", "rose", "violet"]
    readonly property var bucketColors: [bucket1, bucket2, bucket3, bucket4, bucket5, bucket6, bucket7, bucket8]
    readonly property var bucketTextColors: [bucket1Text, bucket2Text, bucket3Text, bucket4Text, bucket5Text, bucket6Text, bucket7Text, bucket8Text]

    function bucketNumber(tone) {
        if (typeof tone === "number")
            return tone >= 1 && tone <= bucketCount ? Math.floor(tone) : 0
        const m = /^bucket([0-9]+)$/.exec(String(tone))
        const n = m ? Number(m[1]) : 0
        return n >= 1 && n <= bucketCount ? n : 0
    }
    function toneBase(tone) {
        const b = bucketNumber(tone)
        if (b > 0)
            return bucketColors[b - 1]
        switch (tone) {
        case "info": case "blue": return toneBlue
        case "ok": case "green": return toneGreen
        case "warn": case "yellow": return toneYellow
        case "orange": return toneOrange
        case "danger": case "red": return toneRed
        case "purple": return tonePurple
        default: return muted
        }
    }
    function toneText(tone) {
        const b = bucketNumber(tone)
        if (b > 0)
            return bucketTextColors[b - 1]
        switch (tone) {
        case "info": case "blue": return toneBlueText
        case "ok": case "green": return toneGreenText
        case "warn": case "yellow": return toneYellowText
        case "orange": return toneOrangeText
        case "danger": case "red": return toneRedText
        case "purple": return tonePurpleText
        default: return text
        }
    }
    function isNeutral(tone) {
        return bucketNumber(tone) === 0 && ["info", "ok", "warn", "danger", "blue", "green",
                                            "yellow", "orange", "red", "purple"].indexOf(tone) < 0
    }
    // The fill under tone text: the tone at toneTint, or --sui-tint for neutral.
    function toneFill(tone) {
        return isNeutral(tone) ? tint : alpha(toneBase(tone), toneTint)
    }
    function toneBorder(tone) {
        return isNeutral(tone) ? line : alpha(toneBase(tone), toneBorderAmount)
    }
    // Health dots: "ok" | "held" | "failing" | "none".
    function statusColor(status) {
        switch (status) {
        case "ok": return ok
        case "held": return toneYellow
        case "failing": return toneRed
        default: return "transparent"
        }
    }

    // `color` at `amount` of its opacity: CSS color-mix(in srgb, c N%, transparent).
    function alpha(c, amount) {
        return Qt.rgba(c.r, c.g, c.b, c.a * amount)
    }

    function _firstInstalled(candidates, fallback) {
        const installed = Qt.fontFamilies().map(f => f.toLowerCase())
        for (const family of candidates) {
            if (family === "monospace" || installed.indexOf(family.toLowerCase()) >= 0)
                return family
        }
        return fallback
    }
}
